language: haskell

sudo: false
cache:
  directories:
    - $HOME/.stack

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/7.10.2/bin:$PATH

env:
  global:
    - GH_NAME="suoe.travis"
    - secure: DEPshqQPfUk8V2i4E07HGQxXw2WWHt8pvyrJYqbFYIKLWAAM8o+4jus8clcYlkUyvJoHUSC6aq0CHJJg2b8hYcN+BhBPvzreig+m+jVr7cP0BTp8GJgcwkZ4OLb36xNazQMpPUEkih6zWkX/6Wtvxg5ayvaxlxzTXQ/x2NJzWG8TDA8KQuG60x70ZRbb1ZyZGCdzNVgJC+dLZXJ/mUGx1Gl8v7AhxY+tIVyZ1VEaDTHyIfngwoUk+azGMh37ZhPNqYmhn7R4kHvv5Kvmh+05EMFq3eugg8TSWCdYTV4HCPW6bhULWu/tIOTu5dgBZKjmFBadhZThAXZS9LsUeKQ2oFFd6RwXuyRwYydGi2E1zSifO2/piaSIoXJ980Rc7t9CgXqnTvwjYwlWjev2ZNX3zXw7uZ/m7gnFK1BkSxLE3jZDRfQichTgFLOGUfY2IqACvxo2UHQn+ediU71zkbYksDjuZZS/ukrwi76bL1KUXkeLUB2kVrTRX5Vq4RBk/aW48a8dbk+ZBITZbZafvSJyMSDV2P0moY/USdNVMSXktAiJdnDGQxqYv3WyzmR5KogG2R3QfCN0Ihzn9gkhdka1zulNdNTbBcNaGtjvlGT70gDyQjfzZaDLhIh8zwF7yGKfiAgvDUSGjevYFJHmzgO5B/M6irZP8y9aiuxnPBnuJ6M=

install:
  - stack setup --no-terminal

before_script:
  - git config --global user.name "$GH_NAME"
  - git config --global user.email "$GH_EMAIL"
  - openssl aes-256-cbc -K $encrypted_dbf7ac7fda1f_key -iv $encrypted_dbf7ac7fda1f_iv -in key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - cd blog
  - stack ghc site.hs
  - ./site build

after_success:
  - cd _site
  - export REMOTE=$(git config remote.origin.url)
  - git remote add github $REMOTE
  - git add .
  - git status
  - git commit -m "by Travis (build $TRAVIS_BUILD_NUMBER)"
  - git push github master
