baseURL = "https://suoe.github.io/"
languageCode = "ja"
title = "Î”Rate"
theme = "beautifulhugo"
hasCJKLanguage = true

pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
  comments = true

[Author]
  name = "Sunao"
  github = "suoe"
  twitter = "suna0oo"

[[menu.main]]
  name = "Blog"
  url = "post"
  weight = 1

[[menu.main]]
  name = "Repository"
  url = "https://github.com/suoe/suoe.github.io"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 1
